global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'auction-svc'
        - 'search-svc'
        - 'bid-svc'
